In [1]:
import os
import pandas as pd
import numpy as np
from numpy.linalg import inv

Question 1: Updload Laptop File into Dataframe.

In [2]:
laptop_df = pd.read_csv('laptop_data.csv', engine='python')

In [3]:
pd.__version__

'2.2.3'

In [4]:
laptop_df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

Q2. Records count
How many records are in the dataset?

In [5]:
len(laptop_df)

2160

Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [6]:
unique_laptops = list(laptop_df.Brand.unique())

In [7]:
len(unique_laptops)

27

In [8]:
laptop_df.Brand.value_counts() 

Brand
Asus                415
HP                  368
Lenovo              366
MSI                 308
Acer                137
Apple               116
Dell                 84
Microsoft            77
Gigabyte             48
Razer                37
Medion               32
LG                   32
Alurin               29
PcCom                24
Samsung              22
Dynabook Toshiba     19
Vant                 11
Deep Gaming           8
Primux                8
Innjoo                6
Thomson               4
Prixton               3
Millenium             2
Denver                1
Jetwing               1
Realme                1
Toshiba               1
Name: count, dtype: int64

Q4. Missing values
How many columns in the dataset have missing values?

In [9]:
laptop_df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [10]:
laptop_df[laptop_df['Brand'] == 'Dell']['Final Price'].max()

np.float64(3936.0)

Q6. Median value of Screen
Find the median value of Screen column in the dataset.
Next, calculate the most frequent value of the same Screen column.
Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
Now, calculate the median value of Screen once again.

In [11]:
screen_median = laptop_df.Screen.median()

In [12]:
screen_median

np.float64(15.6)

In [13]:
screen_mode = laptop_df.Screen.mode()

In [14]:
screen_mode

0    15.6
Name: Screen, dtype: float64

In [15]:
laptop_df.Screen.fillna(0).median()

np.float64(15.6)

In [16]:
laptop_df.Screen.fillna(0).value_counts()

Screen
15.60    1009
14.00     392
16.00     174
17.30     161
13.30     131
16.10      48
17.00      33
13.00      27
15.00      21
13.40      19
13.50      19
11.60      16
14.20      14
12.30      13
13.60      11
14.10      11
16.20      10
15.30       8
10.50       7
12.40       6
14.40       6
15.40       5
0.00        4
12.00       4
18.00       3
14.50       3
13.90       2
12.50       1
10.95       1
10.10       1
Name: count, dtype: int64

Q7. Sum of weights
Select all the "Innjoo" laptops from the dataset.
Select only columns RAM, Storage, Screen.
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Compute the inverse of XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?

In [17]:
innjoo_df = laptop_df[laptop_df['Brand'] == 'Innjoo' ]

In [18]:
innjoo_df = innjoo_df.reset_index(drop=True)

In [19]:
innjoo_df = innjoo_df[['RAM', 'Storage', 'Screen']]

In [20]:
innjoo_df

RAM  Storage  Screen
0    8      256    15.6
1    8      512    15.6
2    4       64    14.1
3    6       64    14.1
4    6      128    14.1
5    6      128    14.1

In [21]:
x = innjoo_df.to_numpy()

In [22]:
x

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [23]:
transpose_x = x.transpose()

In [24]:
transpose_x

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [25]:
xtx = np.matmul(transpose_x,x)

In [26]:
xtx

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [27]:
inverse_xtx = inv(xtx)

In [28]:
inverse_xtx

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [29]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [30]:
new_x = np.matmul(inverse_xtx, transpose_x)

In [31]:
w = np.matmul(new_x, y)

In [32]:
w

array([45.58076606,  0.42783519, 45.29127938])

In [33]:
w.sum()

np.float64(91.2998806299555)